
POST http://localhost:3001/api/preguntas/
Content-Type: application/json

{
    "repuesto": "Amortiguadores Delanteros",
    "marca": " Ford Fiesta 1.8 2010",
    "nombre": "Harrison Otalora",
    "important": true
}